dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm update
- npm install -g @angular/cli
- ng build --prod --base-href=/category-app-client/
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng e2e
after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/category-app
  project_name: catapp
  on:
    branch: master
env:
  global:
    secure: Che/jmMIATnhpKr1qfxzsWhlMrUVR19FygPPymmrUE5zaAyhhqmQwPQDj0DwzwiG5mGbeamCFRhRJXWEl2Ir0xFMT67HA66MPKacnz5+V4xZaEDBAU0ZXuCwOLb2RxGMuEhBx5xQXir5m+k0HbYn+YMeJNX4LMqDPHFlMv6ThxwELlMHvgwTddprRNQju3h+sUZLMPP29O6RiVJK3cOuu66AbTcX0Q5rqCBc98Svxml+0rYo3lXQwvTrINftxDM/CrhSTCU/7mB4BAF7Q/4mtMBZnPjZIaLzpmcvnSx7TFWwxcY23ldRbWm5Qclezwf7Y9O9AwVLm7BnZ+Ob/kVleZwSOslnSkmTh1Uk5t19N07Ygef5HCBuF5o3mRAao/3X4Thg6t2Qz8iVDWm61M7yGWsYDeatajMExTxpwDDk80xk6RLDVk7R3B0bOXH2w1YFbvBLgiDoE8StK+5jd1QylSftpUaBOoKIIoWHysU3ZvvIWnPTaI0Z0WJOC7peQjDwKLPSL9ZWSeG8xrWU8RVSQEq8DJsp4VNZELKGQi6dubPf/mf3APZfZ1v2xwVMLxFV0lHPkDSuyqHYb8Oznyi7WX/S9exqPwwQ0oNb3Y9/SoqbK8+hNLxxB4M3i+bTgDCySwfxeIbv0DxFICe1O5Bgkm3M429kb4MC+94UdVA5R7g=
