dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm install -g @angular/cli
- ng build --prod --base-href=/category-app-client/
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: "dist/category-app"
  project_name: "catapp"
  
  on:
    branch: master
env:
  global:
    secure: DfBf+XCJG+QSDdcuIJOJ0Lp1tJWKzXEiJOohelT5anG/f0G5bZZUQejr0RHn2ec6J0OEzdj4fM8WfvreNAVrzBcbznK0oklM9tbbEoCh0wAOrYG22x5F9IcLcecjpWZDEZfvCOyzJzwNh/qxv6q6cX0AOKVXhhoRYmJFM1lNYTOObwXyam/eLI5NXMKdGi22Ua63chj3BGK4D8QBBxLGFygJYAJWUj0tdga+2ORkvDHOFam/gp4fxq51x1pmdXB0PQFCBSSfjNXX2RFvLg6UrKHzwD4LDTIqbsK3N2V9muklIWISWaR+t0G/tOPs10afv36nDhhtjmlG17dBhNzrQMx2UvfZUwkIsdT+0zdgc5lO9ejNiDYNVPMXg2fsKER8PJEbsc+2temJ7CGjivqIyjCDP+NdMOdLB61IyxQqZRH2auP4E/6zyu4byskA/diHlMp56LswXQdTUKYKsifmVc4jtmbiLP/OMnQ2Q3aNVnOs/4jcnR0Z2h8RNgzY4EaYz5VuFgwn7jYE6W/TMhlqp2zoQFyP/rjP/uXBbVqaPOr5ho7TWpJNRr4UxU2juPr78O7SlOIF9CU71oYD6M0rvawNopeIpmHVktg+qEQ7hhhsfkaDhxoY/uC2dpUFMkPuEJ3eYymOPocdwcrNkkgyR2HrDVwJHM3Hs+Awi6diWK4=
