dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm update
- npm install -g @angular/cli
- ng build --prod --base-href=/category-app-client/
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- ng e2e --protractor-config='e2e/ci.protractor.conf.js'
after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api_key:
    secure: 5JmNIcN6XJ0bYPh9G72DvQTQdL4zBwJHaSjtXP4oB2Y7/dMId7GyscwWM4EPiua/nJpVA0Lh8p+J+vAu9OAmN//8NNHpYT/pAoLR6KG71eMRsUgrhK5HU+VcByk79VcW4T+ZuIkk190RlXZEqYh+cg7z/HsSHVrBqUN3/5jaayi0zRyT0NKLLiTvtFWzMYS1hwNT/kieoQal9wGiibCMxBCh8EgFOtNcq8DN0gAmlIPKOR/E3BIns8EnV4vrCAjCqKpRS17/XwiKM7R9+/TVf/EhRW2RjAkHFo/8B5JTs9GJlnrFamUf4LXt6qUZbKPP/cJld3uP7Y81niAbgMeGzpmyKPdG6lj+RXTSYQhPB8R1nmrAvKN1EXl06dKG7hghb19DOjQNVJko/JXhrdRSJXsjBiXnKho7ptRQf++SBNPn4oRzXPt3DUGlBA3vzn5sCADjU3jvyUb3IViDVYPUCNKSG1eGzwyQ5R7oJTrkaZxVvErOD3JhWSLmRigz1A7uomHjtHzvKfCkpIlTLUeTsD5fzYe7PrxuZOFaL1Jp0+vbuUgOhLsttOuqFpOuSq0eOD/5RB+61GiwNNcVIElqQWgIEqVIJQYXgJ7yUbj3LI1Xth9ogt2PvfHYENdUk2AOOIhy2lnYVkD6FWCHJn3P4KtTvue16DJExkjUs2aPs74=
  on:
    all_branches: true
