dist: trusty
sudo: false
language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
  - "./node_modules"
install:
- npm install
before_script:
- npm update
- npm install -g @angular/cli
- ng build --prod --base-href=/category-app-client/
script:
- npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
- npm run ci-e2e
after_script:
- cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  provider: heroku
  api_key:
    secure: MFJ1zFWCQcV+ags6YJtMKZdA5D+4AlLhxHOyr2OtHrduVoQd03TDCoXLSnXkZcPDu97vsNfnWG+K1wHDgsKVfGGFQzJEmjqvGWGid5DvSI1C/hWisBqMuqsb0CDWku50AoZcT6+69Rsza7RyleWdb0ipHjWh+NWEklr4bJLcpehn4uyf+7oZ0OmLaehsVo2t0ThK4AaztVJcocVuNUGAdXqIkBbKEBc5ybWXnB1j6UUWPDEnd+sLir+HF+buc1L2Q9bwQJFt5OWerubDQgvcCc/uZLiv6SmvpsRjIeMddZXl8PJfwiUrIHGfBRn/BcJQnKpY/b0xJXU4SS/EMID2+Wpt6XX2v5DLbaguPAxVoh90riCN1hj7dynMHFX+Pzj4xIg0MTLvP4T+NtGhvX9m6aooA6sRwFbER7v1J8wQQ34KLf4ctudVnc1Dc+MmJF31gKqqfBeSqkH3Iv32Gn/oOvs+7+BYMaAi3U1K/BSkqt4QRGzxZl/vyXarmtpNgCiwkTTYUYi5yiAlDDUjsOHwj2t/n1BjQTyl0QZL00EbViy8DYrxRRyJSInb5jJze3a6e2OKx8f/F8dZ4sDsfUwjmEB+8gX8PWufyW7l3bcQmcr38QGztwoozr2OlA0X2uyh5WyD+G8SsmIO5MIThIbXk39P50mt/fq+pjWs+jxJteU=
  on:
    all_branches: true
